spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      group-id: seungkyu
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000

server:
  port: 12042


SWAGGER:
  URL: ${SWAGGER_URL}

springdoc:
  api-docs:
    path: /notification/v3/api-docs
  swagger-ui:
    url: /notification/v3/api-docs
    path: /notification/swagger