KAKAO:
  REST_API_KEY: ${KAKAO_REST_API_KEY}
  REDIRECT_URI: ${KAKAO_REDIRECT_URI}


JWT:
  SECRET: ${JWT_SECRET}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      group-id: seungkyu
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 12041
  tomcat:
    threads:
      max: 20
      min-spare: 10

springdoc:
  api-docs:
    path: /user/v3/api-docs
  swagger-ui:
    url: /user/v3/api-docs
    path: /user/swagger

SWAGGER:
  URL: ${SWAGGER_URL}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${AWS_BUCKET}

GOOGLE:
  AUTH:
    CLIENT_ID: ${GOOGLE_AUTH_CLIENT_ID}
    CLIENT_SECRET: ${GOOGLE_AUTH_CLIENT_SECRET}
    REDIRECT_URI: ${GOOGLE_AUTH_REDIRECT_URI}