KAKAO:
  REST_API_KEY: ${KAKAO_REST_API_KEY}
  REDIRECT_URI: ${KAKAO_REDIRECT_URI}


JWT:
  SECRET: ${JWT_SECRET}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      group-id: seungkyu
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 12041

springdoc:
  api-docs:
    path: /user/v3/api-docs
  swagger-ui:
    url: /user/v3/api-docs
    path: /user/swagger

SWAGGER:
  URL: ${SWAGGER_URL}

IMAGE:
  PATH: ${IMAGE_PATH}
  SERVER_NAME: ${IMAGE_SERVER_NAME}


GOOGLE:
  AUTH:
    CLIENT_ID: ${GOOGLE_AUTH_CLIENT_ID}
    CLIENT_SECRET: ${GOOGLE_AUTH_CLIENT_SECRET}
    REDIRECT_URI: ${GOOGLE_AUTH_REDIRECT_URI}