KAKAO:
  REST_API_KEY: ${KAKAO_REST_API_KEY}
  REDIRECT_URI: ${KAKAO_REDIRECT_URI}


JWT:
  SECRET: ${JWT_SECRET}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}


server:
  port: 12041

springdoc:
  api-docs:
    path: /user/v3/api-docs
  swagger-ui:
    url: /user/v3/api-docs
    path: /user/swagger

SWAGGER:
  URL: ${SWAGGER_URL}

SERVER:
  NAME: ${SERVER_ADDRESS}

IMAGE:
  PATH: ${IMAGE_PATH}

