version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ${MONGO_DB_DATA}:/data
      - ./mongo.key:/etc/mongo/mongodb.key:ro  # 로컬에서 만든 keyfile을 /etc/mongo/mongodb.key로 마운트
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    command: [ "--replSet", "rs0", "--keyFile", "/etc/mongo/mongodb.key" ]
    networks:
      - vp

networks:
  vp:
    driver: bridge
    name: vp
    external: true