server:
  port: 12043

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

springdoc:
  api-docs:
    path: /schedule/v3/api-docs
  swagger-ui:
    url: /schedule/v3/api-docs
    path: /schedule/swagger

SWAGGER:
  URL: ${SWAGGER_URL}

