server:
  port: 12043

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
    kafka:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      producer:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      consumer:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
        group-id: seungkyu
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

springdoc:
  api-docs:
    path: /schedule/v3/api-docs
  swagger-ui:
    url: /schedule/v3/api-docs
    path: /schedule/swagger

SWAGGER:
  URL: ${SWAGGER_URL}

