server:
  port: 12040

spring:
  cloud:
    gateway:
      routes:
        - id: jenkins
          uri: ${JENKINS_URI}
          predicates:
            - Path=/jenkins/**

        - id: user
          uri: ${USER_URI}
          predicates:
            - Path=/user/**, /api/v1/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user
                fallbackUri: forward:/fallback/user
        - id: user-security
          uri: ${USER_URI}
          predicates:
            - Path=/api/v1/friend/**
          filters:
            - AuthorizationFilter
            - name: CircuitBreaker
              args:
                name: user
                fallbackUri: forward:/fallback/user

        - id: notification
          uri: ${NOTIFICATION_URI}
          predicates:
            - Path=/notification/**

        - id: notification-security
          uri: ${NOTIFICATION_URI}
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - AuthorizationFilter

        - id: schedule
          uri: ${SCHEDULE_URI}
          predicates:
            - Path=/schedule/**
          filters:
            - name: CircuitBreaker
              args:
                name: schedule
                fallbackUri: forward:/fallback/schedule

        - id: schedule-security
          uri: ${SCHEDULE_URI}
          predicates:
            - Path=/api/v1/fixed-personal-schedule/**
          filters:
            - AuthorizationFilter
            - name: CircuitBreaker
              args:
                name: schedule
                fallbackUri: forward:/fallback/schedule


JWT:
  SECRET: ${JWT_SECRET}


resilience4j:
  circuitbreaker:
    instances:
      user:
        sliding-window-size: 10
        minimum-number-of-calls: 4
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 4
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50

      schedule:
        sliding-window-size: 10
        minimum-number-of-calls: 4
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 4
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
  timelimiter:
    instances:
      user:
        timeout-duration: 8s

      schedule:
        timeout-duration: 8s

logging:
  level:
    io.github.resilience4j.circuitbreaker: debug