server:
  port: 12040

spring:
  cloud:
    gateway:
      routes:
        - id: jenkins
          uri: ${JENKINS_URI}
          predicates:
            - Path=/jenkins/**

        - id: user
          uri: ${USER_URI}
          predicates:
            - Path=/user/**, /api/v1/user/**

        - id: notification
          uri: ${NOTIFICATION_URI}
          predicates:
            - Path=/notification/**, /api/v1/notification/**