server:
  port: 12040

spring:
  cloud:
    gateway:
      routes:
        - id: jenkins
          uri: ${JENKINS_URI}
          predicates:
            - Path=/jenkins/**

        - id: user
          uri: ${USER_URI}
          predicates:
            - Path=/user/**, /api/v1/user/**
        - id: user-security
          uri: ${USER_URI}
          predicates:
            - Path=/api/v1/friend/**
          filters:
            - AuthorizationFilter

        - id: notification
          uri: ${NOTIFICATION_URI}
          predicates:
            - Path=/notification/**

        - id: notification-security
          uri: ${NOTIFICATION_URI}
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - AuthorizationFilter

        - id: schedule
          uri: ${SCHEDULE_URI}
          predicates:
            - Path=/schedule/**

        - id: schedule-securitu
          uri: ${SCHEDULE_URI}
          predicates:
            - Path=/api/v1/schedule/**
          filters:
            - AuthorizationFilter


JWT:
  SECRET: ${JWT_SECRET}