services:
  user:
    image: user:1.0.0
    container_name: user
    networks:
      - vp
    ports:
      - "12041:12041"
    env_file:
      - /home/ec2-user/.env
    volumes:
      - user_volume:/image

networks:
  vp:
    external: true

volumes:
  user_volume:
    driver: local